.TH "Appender.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Appender.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <log4cpp/Priority.hh>\fP
.br
\fC#include <log4cpp/Layout.hh>\fP
.br
\fC#include <log4cpp/LoggingEvent.hh>\fP
.br
\fC#include <log4cpp/threading/Threading.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::Appender\fP"
.br
.RI "\fIImplement this interface for your own strategies for printing log statements. \fP"
.ti -1c
.RI "class \fBlog4cpp::Appender::AppenderMapStorage\fP"
.br
.ti -1c
.RI "class \fBlog4cpp::Appender::AppenderMapStorageInitializer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::set< Appender * > \fBlog4cpp::AppenderSet\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class LOG4CPP_EXPORT \fBlog4cpp::Filter\fP"
.br
.ti -1c
.RI "static Appender::AppenderMapStorageInitializer \fBlog4cpp::appenderMapStorageInitializer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
