.TH "BasicConfigurator.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicConfigurator.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::BasicConfigurator\fP"
.br
.RI "\fIThis class implements a trivial default configuration for \fBlog4cpp\fP: it adds a \fBFileAppender\fP that logs to stdout and uses a \fBBasicLayout\fP to the root \fBCategory\fP. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
