.TH "CategoryStream.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoryStream.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <log4cpp/Priority.hh>\fP
.br
\fC#include <ios>\fP
.br
\fC#include <log4cpp/Manipulator.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::CategoryStream\fP"
.br
.RI "\fIThis class enables streaming simple types and objects to a category. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG4CPP_EXPORT CategoryStream & \fBlog4cpp::eol\fP (CategoryStream &os)"
.br
.RI "\fIeol manipulator \fP"
.ti -1c
.RI "LOG4CPP_EXPORT CategoryStream & \fBlog4cpp::left\fP (CategoryStream &os)"
.br
.RI "\fIleft manipulator \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class LOG4CPP_EXPORT \fBlog4cpp::Category\fP"
.br
.ti -1c
.RI "class LOG4CPP_EXPORT \fBlog4cpp::CategoryStream\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
