.TH "deprecated" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
 
.IP "\fBMember \fBlog4cpp::Category::getAppender\fP() const  \fP" 1c
use getAppender(const std::string&) 
.PP
.PP
 
.IP "\fBMember \fBlog4cpp::Category::ownsAppender\fP() const  \fP" 1c
use ownsAppender(Appender*) 
.PP
.PP
 
.IP "\fBMember \fBlog4cpp::Category::setAppender\fP(Appender &appender) \fP" 1c
use addAppender(Appender&) instead. 
.PP
use addAppender(Appender*) or removeAllAppenders() instead. 
.PP
.PP
 
.IP "\fBClass \fBlog4cpp::SimpleConfigurator\fP \fP" 1c
As of version 0.3.2 \fBlog4cpp\fP includes a log4j format compatible PropertyConfigurator, removing the need for SimpleConfigurator. This class will be removed in 0.4.0. 
.PP

