.TH "DummyThreads.cpp" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyThreads.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/threading/Threading.hh>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.ti -1c
.RI "namespace \fBlog4cpp::threading\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static std::string \fBlog4cpp::threading::getThreadId\fP ()"
.br
.RI "\fIReturn an identifier for the current thread. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
