.TH "Export.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Export.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOG4CPP_EXPORT\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOG4CPP_EXPORT"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
