.TH "HierarchyMaintainer.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HierarchyMaintainer.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <log4cpp/Category.hh>\fP
.br
\fC#include <log4cpp/threading/Threading.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::HierarchyMaintainer\fP"
.br
.RI "\fI\fBHierarchyMaintainer\fP is an internal \fBlog4cpp\fP class. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
