.TH "LevelEvaluator.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelEvaluator.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/TriggeringEventEvaluator.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::LevelEvaluator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBh_3491ecd0_3891_4902_b3ba_15b15d98ae49\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define h_3491ecd0_3891_4902_b3ba_15b15d98ae49"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
