.TH "Localtime.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Localtime.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <time.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlog4cpp::localtime\fP (const ::time_t *time,::tm *t)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
