.TH "log4cpp::Appender::AppenderMapStorageInitializer" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::Appender::AppenderMapStorageInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Appender.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppenderMapStorageInitializer\fP ()"
.br
.ti -1c
.RI "\fB~AppenderMapStorageInitializer\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer ()"
.SS "log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
