.TH "log4cpp::HierarchyMaintainer" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::HierarchyMaintainer \- 
.PP
\fBHierarchyMaintainer\fP is an internal \fBlog4cpp\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HierarchyMaintainer.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, \fBCategory\fP * > \fBCategoryMap\fP"
.br
.ti -1c
.RI "typedef void(* \fBshutdown_fun_ptr\fP )()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHierarchyMaintainer\fP ()"
.br
.ti -1c
.RI "virtual \fB~HierarchyMaintainer\fP ()"
.br
.ti -1c
.RI "virtual \fBCategory\fP * \fBgetExistingInstance\fP (const std::string &name)"
.br
.ti -1c
.RI "virtual \fBCategory\fP & \fBgetInstance\fP (const std::string &name)"
.br
.ti -1c
.RI "virtual std::vector< \fBCategory\fP * > * \fBgetCurrentCategories\fP () const "
.br
.ti -1c
.RI "virtual void \fBshutdown\fP ()"
.br
.ti -1c
.RI "void \fBregister_shutdown_handler\fP (\fBshutdown_fun_ptr\fP handler)"
.br
.ti -1c
.RI "virtual void \fBdeleteAllCategories\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBHierarchyMaintainer\fP & \fBgetDefaultMaintainer\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBCategory\fP * \fB_getExistingInstance\fP (const std::string &name)"
.br
.ti -1c
.RI "virtual \fBCategory\fP & \fB_getInstance\fP (const std::string &name)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCategoryMap\fP \fB_categoryMap\fP"
.br
.ti -1c
.RI "\fBthreading::Mutex\fP \fB_categoryMutex\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBLog4cppCleanup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHierarchyMaintainer\fP is an internal \fBlog4cpp\fP class. 

It is responsible for maintaining the hierarchy of Categories. Applications should not have to use this class directly. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::map<std::string, \fBCategory\fP*> \fBlog4cpp::HierarchyMaintainer::CategoryMap\fP"
.SS "typedef void(* \fBlog4cpp::HierarchyMaintainer::shutdown_fun_ptr\fP)()"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::HierarchyMaintainer::HierarchyMaintainer ()"
.SS "log4cpp::HierarchyMaintainer::~HierarchyMaintainer ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBCategory\fP * log4cpp::HierarchyMaintainer::_getExistingInstance (const std::string & name)\fC [protected, virtual]\fP"
.SS "\fBCategory\fP & log4cpp::HierarchyMaintainer::_getInstance (const std::string & name)\fC [protected, virtual]\fP"
.SS "void log4cpp::HierarchyMaintainer::deleteAllCategories ()\fC [virtual]\fP"
.SS "std::vector< \fBCategory\fP * > * log4cpp::HierarchyMaintainer::getCurrentCategories () const\fC [virtual]\fP"
.SS "\fBHierarchyMaintainer\fP & log4cpp::HierarchyMaintainer::getDefaultMaintainer ()\fC [static]\fP"
.SS "\fBCategory\fP * log4cpp::HierarchyMaintainer::getExistingInstance (const std::string & name)\fC [virtual]\fP"
.SS "\fBCategory\fP & log4cpp::HierarchyMaintainer::getInstance (const std::string & name)\fC [virtual]\fP"
.SS "void log4cpp::HierarchyMaintainer::register_shutdown_handler (\fBshutdown_fun_ptr\fP handler)"
.SS "void log4cpp::HierarchyMaintainer::shutdown ()\fC [virtual]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class Log4cppCleanup\fC [friend]\fP"
.SH "Member Data Documentation"
.PP 
.SS "\fBCategoryMap\fP \fBlog4cpp::HierarchyMaintainer::_categoryMap\fP\fC [protected]\fP"
.SS "\fBthreading::Mutex\fP \fBlog4cpp::HierarchyMaintainer::_categoryMutex\fP\fC [mutable, protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
