.TH "log4cpp::SyslogAppender" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::SyslogAppender \- 
.PP
\fBSyslogAppender\fP sends LoggingEvents to the local syslog system.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SyslogAppender.hh>\fP
.PP
Inherits \fBlog4cpp::LayoutAppender\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyslogAppender\fP (const std::string &name, const std::string &syslogName, int facility=LOG_USER)"
.br
.RI "\fIInstantiate a \fBSyslogAppender\fP with given name and name and facility for syslog. \fP"
.ti -1c
.RI "virtual \fB~SyslogAppender\fP ()"
.br
.ti -1c
.RI "virtual bool \fBreopen\fP ()"
.br
.RI "\fICalls closelog(3) and openlog(3). \fP"
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.RI "\fICalls closelog(3) to close the syslog file descriptor. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBtoSyslogPriority\fP (\fBPriority::Value\fP priority)"
.br
.RI "\fITranslates a \fBlog4cpp\fP priority to a syslog priority. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBopen\fP ()"
.br
.RI "\fICalls openlog(3). \fP"
.ti -1c
.RI "virtual void \fB_append\fP (const \fBLoggingEvent\fP &event)"
.br
.RI "\fISends a \fBLoggingEvent\fP to syslog. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const std::string \fB_syslogName\fP"
.br
.ti -1c
.RI "int \fB_facility\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSyslogAppender\fP sends LoggingEvents to the local syslog system. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::SyslogAppender::SyslogAppender (const std::string & name, const std::string & syslogName, int facility = \fCLOG_USER\fP)"
.PP
Instantiate a \fBSyslogAppender\fP with given name and name and facility for syslog. Note that the C syslog API is process global, so instantion of a second \fBSyslogAppender\fP will 'overwrite' the syslog name of the first. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name of the \fBAppender\fP 
.br
\fIsyslogName\fP The ident parameter in the openlog(3) call. 
.br
\fIfacility\fP The syslog facility to log to. Defaults to LOG_USER. 
.RE
.PP

.SS "virtual log4cpp::SyslogAppender::~SyslogAppender ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "virtual void log4cpp::SyslogAppender::_append (const \fBLoggingEvent\fP & event)\fC [protected, virtual]\fP"
.PP
Sends a \fBLoggingEvent\fP to syslog. \fBParameters:\fP
.RS 4
\fIevent\fP the \fBLoggingEvent\fP to log. 
.RE
.PP

.PP
Implements \fBlog4cpp::AppenderSkeleton\fP.
.SS "virtual void log4cpp::SyslogAppender::close ()\fC [virtual]\fP"
.PP
Calls closelog(3) to close the syslog file descriptor. 
.PP
Implements \fBlog4cpp::AppenderSkeleton\fP.
.SS "virtual void log4cpp::SyslogAppender::open ()\fC [protected, virtual]\fP"
.PP
Calls openlog(3). 
.SS "virtual bool log4cpp::SyslogAppender::reopen ()\fC [virtual]\fP"
.PP
Calls closelog(3) and openlog(3). 
.PP
Reimplemented from \fBlog4cpp::AppenderSkeleton\fP.
.SS "static int log4cpp::SyslogAppender::toSyslogPriority (\fBPriority::Value\fP priority)\fC [static]\fP"
.PP
Translates a \fBlog4cpp\fP priority to a syslog priority. \fBParameters:\fP
.RS 4
\fIpriority\fP The \fBlog4cpp\fP priority. 
.RE
.PP
\fBReturns:\fP
.RS 4
the syslog priority. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int \fBlog4cpp::SyslogAppender::_facility\fP\fC [protected]\fP"
.SS "const std::string \fBlog4cpp::SyslogAppender::_syslogName\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
