.TH "log4cpp::NDC::DiagnosticContext" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::NDC::DiagnosticContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NDC.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiagnosticContext\fP (const std::string &\fBmessage\fP)"
.br
.ti -1c
.RI "\fBDiagnosticContext\fP (const std::string &\fBmessage\fP, const \fBDiagnosticContext\fP &parent)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.ti -1c
.RI "std::string \fBfullMessage\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::NDC::DiagnosticContext::DiagnosticContext (const std::string & message)"
.SS "log4cpp::NDC::DiagnosticContext::DiagnosticContext (const std::string & message, const \fBDiagnosticContext\fP & parent)"
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBlog4cpp::NDC::DiagnosticContext::fullMessage\fP"
.SS "std::string \fBlog4cpp::NDC::DiagnosticContext::message\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
