.TH "log4cpp::OstreamAppender" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::OstreamAppender \- 
.PP
\fBOstreamAppender\fP appends LoggingEvents to ostreams.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OstreamAppender.hh>\fP
.PP
Inherits \fBlog4cpp::LayoutAppender\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOstreamAppender\fP (const std::string &name, std::ostream *stream)"
.br
.ti -1c
.RI "virtual \fB~OstreamAppender\fP ()"
.br
.ti -1c
.RI "virtual bool \fBreopen\fP ()"
.br
.RI "\fIReopens the output destination of this \fBAppender\fP, e.g. \fP"
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.RI "\fIRelease any resources allocated within the appender such as file handles, network connections, etc. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_append\fP (const \fBLoggingEvent\fP &event)"
.br
.RI "\fILog in \fBAppender\fP specific way. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::ostream * \fB_stream\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBOstreamAppender\fP appends LoggingEvents to ostreams. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::OstreamAppender::OstreamAppender (const std::string & name, std::ostream * stream)"
.SS "log4cpp::OstreamAppender::~OstreamAppender ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void log4cpp::OstreamAppender::_append (const \fBLoggingEvent\fP & event)\fC [protected, virtual]\fP"
.PP
Log in \fBAppender\fP specific way. Subclasses of \fBAppender\fP should implement this method to perform actual logging. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP The \fBLoggingEvent\fP to log. 
.RE
.PP

.PP
Implements \fBlog4cpp::AppenderSkeleton\fP.
.SS "void log4cpp::OstreamAppender::close ()\fC [virtual]\fP"
.PP
Release any resources allocated within the appender such as file handles, network connections, etc. 
.PP
Implements \fBlog4cpp::AppenderSkeleton\fP.
.SS "bool log4cpp::OstreamAppender::reopen ()\fC [virtual]\fP"
.PP
Reopens the output destination of this \fBAppender\fP, e.g. the logfile or TCP socket. 
.PP
\fBReturns:\fP
.RS 4
false if an error occured during reopening, true otherwise. 
.RE
.PP

.PP
Reimplemented from \fBlog4cpp::AppenderSkeleton\fP.
.SH "Member Data Documentation"
.PP 
.SS "std::ostream* \fBlog4cpp::OstreamAppender::_stream\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
