.TH "log4cpp::threading::MSScopedLock" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::threading::MSScopedLock \- 
.PP
A simple object wrapper around WaitForSingleObject() and ReleaseMutex().  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSThreads.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMSScopedLock\fP (\fBMSMutex\fP &mutex)"
.br
.ti -1c
.RI "\fB~MSScopedLock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple object wrapper around WaitForSingleObject() and ReleaseMutex(). 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::threading::MSScopedLock::MSScopedLock (\fBMSMutex\fP & mutex)\fC [inline]\fP"
.SS "log4cpp::threading::MSScopedLock::~MSScopedLock ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
