.TH "log4cpp::BasicConfigurator" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::BasicConfigurator \- 
.PP
This class implements a trivial default configuration for \fBlog4cpp\fP: it adds a \fBFileAppender\fP that logs to stdout and uses a \fBBasicLayout\fP to the root \fBCategory\fP.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicConfigurator.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBconfigure\fP ()"
.br
.RI "\fIPerforms a minimal configuration of \fBlog4cpp\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a trivial default configuration for \fBlog4cpp\fP: it adds a \fBFileAppender\fP that logs to stdout and uses a \fBBasicLayout\fP to the root \fBCategory\fP. 

\fBSince:\fP
.RS 4
0.3.2 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void log4cpp::BasicConfigurator::configure ()\fC [static]\fP"
.PP
Performs a minimal configuration of \fBlog4cpp\fP. 

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
