.TH "log4cpp::threading::Mutex" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::threading::Mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PThreads.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "\fB~Mutex\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::threading::Mutex::Mutex ()\fC [inline]\fP"
.SS "log4cpp::threading::Mutex::~Mutex ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void log4cpp::threading::Mutex::lock ()\fC [inline]\fP"
.SS "void log4cpp::threading::Mutex::unlock ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
