.TH "log4cpp::tab" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::tab \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Manipulator.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtab\fP (unsigned int i)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBtab\fP &w)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::tab::tab (unsigned int i)\fC [inline]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBtab\fP & w)\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
