.TH "log4cpp::ConfigureFailure" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::ConfigureFailure \- 
.PP
Exception class for configuration.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configurator.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigureFailure\fP (const std::string &reason)"
.br
.RI "\fIConstructor. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exception class for configuration. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::ConfigureFailure::ConfigureFailure (const std::string & reason)"
.PP
Constructor. \fBParameters:\fP
.RS 4
\fIreason\fP String containing the description of the exception. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
