.TH "log4cpp::BasicLayout" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::BasicLayout \- 
.PP
\fBBasicLayout\fP is a simple fixed format \fBLayout\fP implementation.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicLayout.hh>\fP
.PP
Inherits \fBlog4cpp::Layout\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicLayout\fP ()"
.br
.ti -1c
.RI "virtual \fB~BasicLayout\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBformat\fP (const \fBLoggingEvent\fP &event)"
.br
.RI "\fIFormats the \fBLoggingEvent\fP in \fBBasicLayout\fP style:
.br
 'timeStamp priority category ndc: message'. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBBasicLayout\fP is a simple fixed format \fBLayout\fP implementation. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::BasicLayout::BasicLayout ()"
.SS "log4cpp::BasicLayout::~BasicLayout ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "std::string log4cpp::BasicLayout::format (const \fBLoggingEvent\fP & event)\fC [virtual]\fP"
.PP
Formats the \fBLoggingEvent\fP in \fBBasicLayout\fP style:
.br
 'timeStamp priority category ndc: message'. 
.PP
Implements \fBlog4cpp::Layout\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
