.TH "log4cpp::details::required_params_validator" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::details::required_params_validator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FactoryParams.hh>\fP
.PP
Inherits \fBlog4cpp::details::base_validator_data\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrequired_params_validator\fP (const char *tag, const \fBFactoryParams\fP *params)"
.br
.ti -1c
.RI "template<typename T > \fBoptional_params_validator\fP \fBoptional\fP (const char *param, T &value) const "
.br
.ti -1c
.RI "template<typename T > const \fBrequired_params_validator\fP & \fBoperator()\fP (const char *param, T &value) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::details::required_params_validator::required_params_validator (const char * tag, const \fBFactoryParams\fP * params)\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const \fBrequired_params_validator\fP& log4cpp::details::required_params_validator::operator() (const char * param, T & value) const\fC [inline]\fP"
.SS "template<typename T > \fBoptional_params_validator\fP log4cpp::details::required_params_validator::optional (const char * param, T & value) const\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
