.TH "log4cpp::threading::MSMutex" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::threading::MSMutex \- 
.PP
A simple object wrapper around CreateMutex() and DeleteMutex().  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSThreads.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMSMutex\fP ()"
.br
.ti -1c
.RI "\fB~MSMutex\fP ()"
.br
.ti -1c
.RI "LPCRITICAL_SECTION \fBgetCriticalSection\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple object wrapper around CreateMutex() and DeleteMutex(). 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::threading::MSMutex::MSMutex ()\fC [inline]\fP"
.SS "log4cpp::threading::MSMutex::~MSMutex ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "LPCRITICAL_SECTION log4cpp::threading::MSMutex::getCriticalSection ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
