.TH "log4cpp::PassThroughLayout" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::PassThroughLayout \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PassThroughLayout.hh>\fP
.PP
Inherits \fBlog4cpp::Layout\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBformat\fP (const \fBLoggingEvent\fP &event)"
.br
.RI "\fIFormats the \fBLoggingEvent\fP data to a string that appenders can log. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string log4cpp::PassThroughLayout::format (const \fBLoggingEvent\fP & event)\fC [inline, virtual]\fP"
.PP
Formats the \fBLoggingEvent\fP data to a string that appenders can log. Implement this method to create your own layout format. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP The \fBLoggingEvent\fP. 
.RE
.PP
\fBReturns:\fP
.RS 4
an appendable string. 
.RE
.PP

.PP
Implements \fBlog4cpp::Layout\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
