.TH "log4cpp::PatternLayout::PatternComponent" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::PatternLayout::PatternComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PatternLayout.hh>\fP
.PP
Inherited by \fBlog4cpp::CategoryNameComponent\fP, \fBlog4cpp::FormatModifierComponent\fP, \fBlog4cpp::MessageComponent\fP, \fBlog4cpp::MillisSinceEpochComponent\fP, \fBlog4cpp::NDCComponent\fP, \fBlog4cpp::PriorityComponent\fP, \fBlog4cpp::ProcessorTimeComponent\fP, \fBlog4cpp::SecondsSinceEpochComponent\fP, \fBlog4cpp::StringLiteralComponent\fP, \fBlog4cpp::ThreadNameComponent\fP, and \fBlog4cpp::TimeStampComponent\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PatternComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBappend\fP (\fBstd::ostringstream\fP &out, const \fBLoggingEvent\fP &event)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual log4cpp::PatternLayout::PatternComponent::~PatternComponent ()\fC [inline, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "virtual void log4cpp::PatternLayout::PatternComponent::append (\fBstd::ostringstream\fP & out, const \fBLoggingEvent\fP & event)\fC [pure virtual]\fP"
.PP
Implemented in \fBlog4cpp::StringLiteralComponent\fP, \fBlog4cpp::CategoryNameComponent\fP, \fBlog4cpp::MessageComponent\fP, \fBlog4cpp::NDCComponent\fP, \fBlog4cpp::PriorityComponent\fP, \fBlog4cpp::ThreadNameComponent\fP, \fBlog4cpp::ProcessorTimeComponent\fP, \fBlog4cpp::TimeStampComponent\fP, \fBlog4cpp::SecondsSinceEpochComponent\fP, \fBlog4cpp::MillisSinceEpochComponent\fP, and \fBlog4cpp::FormatModifierComponent\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
