.TH "log4cpp::Appender::AppenderMapStorage" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::Appender::AppenderMapStorage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Appender.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppenderMapStorage\fP ()"
.br
.ti -1c
.RI "\fB~AppenderMapStorage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Appender::AppenderMap * \fB_allAppenders\fP"
.br
.ti -1c
.RI "\fBthreading::Mutex\fP \fB_appenderMapMutex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::Appender::AppenderMapStorage::AppenderMapStorage ()"
.SS "log4cpp::Appender::AppenderMapStorage::~AppenderMapStorage ()"
.SH "Member Data Documentation"
.PP 
.SS "Appender::AppenderMap* \fBlog4cpp::Appender::AppenderMapStorage::_allAppenders\fP"
.SS "\fBthreading::Mutex\fP \fBlog4cpp::Appender::AppenderMapStorage::_appenderMapMutex\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
