.TH "log4cpp::DailyRollingFileAppender" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::DailyRollingFileAppender \- 
.PP
\fBDailyRollingFileAppender\fP is a \fBFileAppender\fP that rolls over the logfile once the next day starts.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DailyRollingFileAppender.hh>\fP
.PP
Inherits \fBlog4cpp::FileAppender\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDailyRollingFileAppender\fP (const std::string &name, const std::string &fileName, unsigned int maxDaysToKeep=\fBmaxDaysToKeepDefault\fP, bool append=true, mode_t mode=00644)"
.br
.ti -1c
.RI "virtual void \fBsetMaxDaysToKeep\fP (unsigned int maxDaysToKeep)"
.br
.ti -1c
.RI "virtual unsigned int \fBgetMaxDaysToKeep\fP () const "
.br
.ti -1c
.RI "virtual void \fBrollOver\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static unsigned int \fBmaxDaysToKeepDefault\fP = 30"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_append\fP (const \fBLoggingEvent\fP &event)"
.br
.RI "\fILog in \fBAppender\fP specific way. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fB_maxDaysToKeep\fP"
.br
.ti -1c
.RI "struct tm \fB_logsTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDailyRollingFileAppender\fP is a \fBFileAppender\fP that rolls over the logfile once the next day starts. 

\fBSince:\fP
.RS 4
1.1.2 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::DailyRollingFileAppender::DailyRollingFileAppender (const std::string & name, const std::string & fileName, unsigned int maxDaysToKeep = \fC\fBmaxDaysToKeepDefault\fP\fP, bool append = \fCtrue\fP, mode_t mode = \fC00644\fP)"
.SH "Member Function Documentation"
.PP 
.SS "void log4cpp::DailyRollingFileAppender::_append (const \fBLoggingEvent\fP & event)\fC [protected, virtual]\fP"
.PP
Log in \fBAppender\fP specific way. Subclasses of \fBAppender\fP should implement this method to perform actual logging. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP The \fBLoggingEvent\fP to log. 
.RE
.PP

.PP
Reimplemented from \fBlog4cpp::FileAppender\fP.
.SS "unsigned int log4cpp::DailyRollingFileAppender::getMaxDaysToKeep () const\fC [virtual]\fP"
.SS "void log4cpp::DailyRollingFileAppender::rollOver ()\fC [virtual]\fP"
.SS "void log4cpp::DailyRollingFileAppender::setMaxDaysToKeep (unsigned int maxDaysToKeep)\fC [virtual]\fP"
.SH "Member Data Documentation"
.PP 
.SS "struct tm \fBlog4cpp::DailyRollingFileAppender::_logsTime\fP\fC [read, protected]\fP"
.SS "unsigned int \fBlog4cpp::DailyRollingFileAppender::_maxDaysToKeep\fP\fC [protected]\fP"
.SS "unsigned int \fBlog4cpp::DailyRollingFileAppender::maxDaysToKeepDefault\fP = 30\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
