.TH "MSThreads.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSThreads.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <windows.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::threading::MSMutex\fP"
.br
.RI "\fIA simple object wrapper around CreateMutex() and DeleteMutex(). \fP"
.ti -1c
.RI "class \fBlog4cpp::threading::MSScopedLock\fP"
.br
.RI "\fIA simple object wrapper around WaitForSingleObject() and ReleaseMutex(). \fP"
.ti -1c
.RI "class \fBlog4cpp::threading::ThreadLocalDataHolder< T >\fP"
.br
.RI "\fIThis class holds Thread local data of type T, i.e. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.ti -1c
.RI "namespace \fBlog4cpp::threading\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNOGDI\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPP_UNDEFINE_NOGDI\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPP_UNDEFINE_WIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static std::string \fBlog4cpp::threading::getThreadId\fP ()"
.br
.RI "\fIReturn an identifier for the current thread. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOG4CPP_UNDEFINE_NOGDI"
.SS "#define LOG4CPP_UNDEFINE_WIN32_LEAN_AND_MEAN"
.SS "#define NOGDI"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
