.TH "NTEventLogAppender.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTEventLogAppender.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows.h>\fP
.br
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <log4cpp/AppenderSkeleton.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::NTEventLogAppender\fP"
.br
.RI "\fI\fBNTEventLogAppender\fP is an \fBAppender\fP that sends LoggingEvents to the Windows event log. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNOGDI\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPP_UNDEFINE_NOGDI\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPP_UNDEFINE_WIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOG4CPP_UNDEFINE_NOGDI"
.SS "#define LOG4CPP_UNDEFINE_WIN32_LEAN_AND_MEAN"
.SS "#define NOGDI"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
