.TH "PortabilityImpl.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PortabilityImpl.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > const T & \fBlog4cpp::min\fP (const T &a, const T &b)"
.br
.ti -1c
.RI "template<typename T > const T & \fBlog4cpp::max\fP (const T &a, const T &b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
