.TH "RemoteSyslogAppender.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoteSyslogAppender.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <log4cpp/LayoutAppender.hh>\fP
.br
\fC#include <log4cpp/Priority.hh>\fP
.br
\fC#include <winsock2.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::RemoteSyslogAppender\fP"
.br
.RI "\fI\fBRemoteSyslogAppender\fP sends LoggingEvents to a remote syslog system. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSyslogLevel\fP { \fBLOG_EMERG\fP =  0, \fBLOG_ALERT\fP =  1, \fBLOG_CRIT\fP =  2, \fBLOG_ERR\fP =  3, \fBLOG_WARNING\fP =  4, \fBLOG_NOTICE\fP =  5, \fBLOG_INFO\fP =  6, \fBLOG_DEBUG\fP =  7 }"
.br
.RI "\fIfrom syslog.h \fP"
.ti -1c
.RI "enum \fBSyslogFacility\fP { \fBLOG_KERN\fP =  (0<<3), \fBLOG_USER\fP =  (1<<3), \fBLOG_MAIL\fP =  (2<<3), \fBLOG_DAEMON\fP =  (3<<3), \fBLOG_AUTH\fP =  (4<<3), \fBLOG_SYSLOG\fP =  (5<<3), \fBLOG_LPR\fP =  (6<<3), \fBLOG_NEWS\fP =  (7<<3), \fBLOG_UUCP\fP =  (8<<3), \fBLOG_CRON\fP =  (9<<3), \fBLOG_AUTHPRIV\fP =  (10<<3), \fBLOG_FTP\fP =  (11<<3), \fBLOG_LOCAL0\fP =  (16<<3), \fBLOG_LOCAL1\fP =  (17<<3), \fBLOG_LOCAL2\fP =  (18<<3), \fBLOG_LOCAL3\fP =  (19<<3), \fBLOG_LOCAL4\fP =  (20<<3), \fBLOG_LOCAL5\fP =  (21<<3), \fBLOG_LOCAL6\fP =  (22<<3), \fBLOG_LOCAL7\fP =  (23<<3) }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSyslogFacility\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fILOG_KERN \fP\fP
kernel messages 
.TP
\fB\fILOG_USER \fP\fP
random user-level messages 
.TP
\fB\fILOG_MAIL \fP\fP
mail system 
.TP
\fB\fILOG_DAEMON \fP\fP
system daemons 
.TP
\fB\fILOG_AUTH \fP\fP
security/authorization messages 
.TP
\fB\fILOG_SYSLOG \fP\fP
messages generated internally by syslogd 
.TP
\fB\fILOG_LPR \fP\fP
line printer subsystem 
.TP
\fB\fILOG_NEWS \fP\fP
network news subsystem 
.TP
\fB\fILOG_UUCP \fP\fP
UUCP subsystem. 
.TP
\fB\fILOG_CRON \fP\fP
clock daemon 
.TP
\fB\fILOG_AUTHPRIV \fP\fP
security/authorization messages (private) 
.TP
\fB\fILOG_FTP \fP\fP
ftp daemon 
.TP
\fB\fILOG_LOCAL0 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL1 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL2 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL3 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL4 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL5 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL6 \fP\fP
reserved for local use 
.TP
\fB\fILOG_LOCAL7 \fP\fP
reserved for local use 
.SS "enum \fBSyslogLevel\fP"
.PP
from syslog.h 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fILOG_EMERG \fP\fP
system is unusable 
.TP
\fB\fILOG_ALERT \fP\fP
action must be taken immediately 
.TP
\fB\fILOG_CRIT \fP\fP
critical conditions 
.TP
\fB\fILOG_ERR \fP\fP
error conditions 
.TP
\fB\fILOG_WARNING \fP\fP
warning conditions 
.TP
\fB\fILOG_NOTICE \fP\fP
normal but significant condition 
.TP
\fB\fILOG_INFO \fP\fP
informational 
.TP
\fB\fILOG_DEBUG \fP\fP
debug-level messages 
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
