.TH "StringUtil.cpp" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringUtil.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StringUtil.hh'\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include 'snprintf.c'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHAVE_SNPRINTF\fP"
.br
.ti -1c
.RI "#define \fBPREFER_PORTABLE_SNPRINTF\fP"
.br
.ti -1c
.RI "#define \fBVSNPRINTF\fP   portable_vsnprintf"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HAVE_SNPRINTF"
.SS "#define PREFER_PORTABLE_SNPRINTF"
.SS "#define VSNPRINTF   portable_vsnprintf"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
