.TH "TriggeringEventEvaluatorFactory.hh" 3 "1 Nov 2017" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggeringEventEvaluatorFactory.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Portability.hh'\fP
.br
\fC#include 'TriggeringEventEvaluator.hh'\fP
.br
\fC#include 'FactoryParams.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::TriggeringEventEvaluatorFactory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.PP

.RI "\fIThe top level namespace for all 'Log for C++' types and classes. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBh_dd233b8b_5c59_4956_9393_6581c95f9779\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define h_dd233b8b_5c59_4956_9393_6581c95f9779"
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
